name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest

    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

      - name: Permission
        run: |
          cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      # Enviar para firebase
      - name: Upload artifact
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
         appId: ${{ secrets.FIREBASE_APP_ID }}
         token: ${{ secrets.FIREBASE_TOKEN }}
         groups: deploy
         file: app/build/outputs/apk/debug/app-debug.apk
