# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup JDK
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Instalar NDK
      - name: Instalar NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Enviar para firebase
      - name: Upload artifact
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
         appId: ${{ secrets.FIREBASE_APP_ID }}
         token: ${{ secrets.FIREBASE_TOKEN }}
         groups: deploy
         file: app/build/outputs/apk/debug/app-debug.apk
